query pools($skip: Int, $limit: Int) {
  pools(first: $limit, skip: $skip, orderBy: txCount, orderDirection: desc) {
    ...PoolData
  }
}

fragment PoolData on Pool {
  id
  volumeUSD
  txCount
  totalValueLockedUSD
  token0 {
    name
    symbol
    id
  }
  token1 {
    name
    symbol
    id
  }
}
