query tokens($skip: Int, $limit: Int) {
    tokens(first: $limit skip: $skip) {
        name
        symbol
        decimals
        totalSupply
        volumeUSD
        totalValueLockedUSD
        txCount
        id
    }
}