query watchpools($IDS: [ID!]) {
  pools(where: { id_in: $IDS }) {
    ...PoolData
  }
}

fragment PoolData on Pool {
  id
  volumeUSD
  txCount
  totalValueLockedUSD
  token0 {
    name
    symbol
    id
  }
  token1 {
    name
    symbol
    id
  }
}
